CREATE VIRTUAL TABLE BUKU_SEARCH USING fts5(KODE_BUKU, JUDUL_BUKU, PENULIS_BUKU, STATUS_BUKU);

CREATE TRIGGER BUKU_SEARCH_BEFORE_UPDATE BEFORE UPDATE ON BUKU BEGIN
    DELETE FROM BUKU_SEARCH WHERE KODE_BUKU=OLD.KODE_BUKU;
END;

CREATE TRIGGER BUKU_SEARCH_BEFORE_DELETE BEFORE DELETE ON BUKU BEGIN
    DELETE FROM BUKU_SEARCH WHERE KODE_BUKU=OLD.KODE_BUKU;
END;

CREATE TRIGGER BUKU_SEARCH_AFTER_UPDATE AFTER UPDATE ON BUKU BEGIN
    INSERT INTO BUKU_SEARCH(KODE_BUKU, JUDUL_BUKU, PENULIS_BUKU, STATUS_BUKU) SELECT KODE_BUKU, JUDUL_BUKU, PENULIS_BUKU, CASE STATUS_BUKU WHEN 0 THEN "Tersedia" ELSE "Dipinjam" END FROM BUKU WHERE  NEW.KODE_BUKU = BUKU.KODE_BUKU;
END;

CREATE TRIGGER BUKU_SEARCH_AFTER_INSERT AFTER INSERT ON BUKU BEGIN
    INSERT INTO BUKU_SEARCH(KODE_BUKU, JUDUL_BUKU, PENULIS_BUKU, STATUS_BUKU) SELECT KODE_BUKU, JUDUL_BUKU, PENULIS_BUKU, CASE STATUS_BUKU WHEN 0 THEN "Tersedia" ELSE "Dipinjam" END FROM BUKU WHERE  NEW.KODE_BUKU = BUKU.KODE_BUKU;
END;

CREATE VIRTUAL TABLE PEMINJAMAN_SEARCH USING fts5(ID_PEMINJAMAN, KODE_BUKU, NAMA_PEMINJAM, TELEPON_PEMINJAM, ALAMAT_PEMINJAM, WAKTU_PINJAM, WAKTU_TENGGANG, WAKTU_KEMBALI);

CREATE TRIGGER PEMINJAMAN_SEARCH_BEFORE_UPDATE BEFORE UPDATE ON PEMINJAMAN BEGIN
    DELETE FROM PEMINJAMAN_SEARCH WHERE ID_PEMINJAMAN=OLD.ID_PEMINJAMAN;
END;

CREATE TRIGGER PEMINJAMAN_SEARCH_BEFORE_DELETE BEFORE DELETE ON PEMINJAMAN BEGIN
    DELETE FROM PEMINJAMAN_SEARCH WHERE ID_PEMINJAMAN=OLD.ID_PEMINJAMAN;
END;

CREATE TRIGGER PEMINJAMAN_SEARCH_AFTER_UPDATE AFTER UPDATE ON PEMINJAMAN BEGIN
    INSERT INTO PEMINJAMAN_SEARCH(ID_PEMINJAMAN, KODE_BUKU, NAMA_PEMINJAM, TELEPON_PEMINJAM, ALAMAT_PEMINJAM, WAKTU_PINJAM, WAKTU_TENGGANG, WAKTU_KEMBALI) SELECT ID_PEMINJAMAN, KODE_BUKU, NAMA_PEMINJAM, TELEPON_PEMINJAM, ALAMAT_PEMINJAM, WAKTU_PINJAM, WAKTU_TENGGANG, WAKTU_KEMBALI FROM PEMINJAMAN WHERE  NEW.ID_PEMINJAMAN = PEMINJAMAN.ID_PEMINJAMAN;
END;

CREATE TRIGGER PEMINJAMAN_SEARCH_AFTER_INSERT AFTER INSERT ON PEMINJAMAN BEGIN
    INSERT INTO PEMINJAMAN_SEARCH(ID_PEMINJAMAN, KODE_BUKU, NAMA_PEMINJAM, TELEPON_PEMINJAM, ALAMAT_PEMINJAM, WAKTU_PINJAM, WAKTU_TENGGANG, WAKTU_KEMBALI) SELECT ID_PEMINJAMAN, KODE_BUKU, NAMA_PEMINJAM, TELEPON_PEMINJAM, ALAMAT_PEMINJAM, WAKTU_PINJAM, WAKTU_TENGGANG, WAKTU_KEMBALI FROM PEMINJAMAN WHERE  NEW.ID_PEMINJAMAN = PEMINJAMAN.ID_PEMINJAMAN;
END;