/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan.ui.forms;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import perpustakaan.classes.Buku;
import perpustakaan.classes.Peminjaman;
import perpustakaan.ui.classes.IMainPanel;
import perpustakaan.util.Util;

/**
 *
 * @author LENOVO
 */
public class DetailPeminjamanPanel extends javax.swing.JPanel implements IMainPanel {

    /**
     * Creates new form DetailBukuPanel
     */
    MainPanel parent;
    Peminjaman peminjaman = null;
    
    public DetailPeminjamanPanel() {
        initComponents();
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }

    public void setParent(MainPanel parent){
        this.parent = parent;
        
    }

    public void init(MainPanel parent){
        setParent(parent);
    }
    @Override
    public void refresh() {
        load(null);
    }

    @Override
    public void load(Object object) {
        if(object == null){
            this.peminjaman = null;
            
            return;
        }
        if(object instanceof Peminjaman){
            Peminjaman p = (Peminjaman)object;
            this.peminjaman = p;
            kodeBukuField.setText(p.kodeBuku);
            idPeminjamanField.setText(""+p.idPeminjaman);
            namaPeminjamField.setText(p.namaPeminjam);
            teleponPeminjamField.setText(p.teleponPeminjam);
            alamatPeminjamField.setText(p.alamatPeminjam);
            waktuTenggangField.setText(p.waktuTenggang.split(" ")[0]);
            waktuPinjamField.setText(p.waktuPinjam.split(" ")[0]);
            if(p.waktuKembali == null){
                kembalikanButton.setVisible(true);
                titleLabel.setText("Daftar Peminjaman / Detail Peminjaman");
                waktuKembaliLabel.setVisible(false);
                waktuKembaliField.setVisible(false);
            }else{
                kembalikanButton.setVisible(false);
                titleLabel.setText("Riwayat Peminjaman / Detail Peminjaman");
                waktuKembaliLabel.setVisible(true);
                waktuKembaliField.setVisible(true);
                waktuKembaliField.setText(p.waktuKembali.split(" ")[0]);
            }
            ImageIcon coverIcon = Buku.findCoverImageIcon(p.kodeBuku);
            if(coverIcon == null){
                coverLabel.setIcon("cover.png");
            }else{
                coverLabel.setIcon(coverIcon);
            }
        }
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
    
    public boolean kembalikan(){
        if(peminjaman.waktuKembali != null){
            return false;
        }
        if(peminjaman.kembalikan()){
            peminjaman.refresh();
            load(peminjaman);
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerKiri = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        tabel = new javax.swing.JPanel();
        tabelkiri = new javax.swing.JPanel();
        coverLabel = new perpustakaan.ui.classes.ImageLabel();
        kembalikanButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tabelkanan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kodeBukuField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        idPeminjamanField = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        namaPeminjamField = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        teleponPeminjamField = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        alamatPeminjamField = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        waktuPinjamLabel = new javax.swing.JLabel();
        waktuPinjamField = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        waktuTenggangLabel = new javax.swing.JLabel();
        waktuTenggangField = new javax.swing.JLabel();
        waktuKembaliLabel = new javax.swing.JLabel();
        waktuKembaliField = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        headerKiri.setOpaque(false);
        headerKiri.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(40, 38, 78));
        titleLabel.setText("Daftar Peminjaman / Detail Peminjaman");
        titleLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        headerKiri.add(titleLabel, gridBagConstraints);

        btnKembali.setBackground(new java.awt.Color(218, 219, 230));
        btnKembali.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(85, 89, 114));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/ui/gambar/icon/kembali.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        headerKiri.add(btnKembali, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        add(headerKiri, gridBagConstraints);

        tabel.setBackground(new java.awt.Color(255, 255, 255));
        tabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        tabel.setMinimumSize(new java.awt.Dimension(0, 0));
        tabel.setLayout(new java.awt.GridBagLayout());

        tabelkiri.setBackground(new java.awt.Color(255, 255, 255));
        tabelkiri.setMinimumSize(new java.awt.Dimension(199, 340));
        tabelkiri.setLayout(new java.awt.GridBagLayout());

        coverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/ui/gambar/cover.png"))); // NOI18N
        coverLabel.setMinimumSize(new java.awt.Dimension(199, 290));
        coverLabel.setPreferredSize(new java.awt.Dimension(199, 290));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        tabelkiri.add(coverLabel, gridBagConstraints);

        kembalikanButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        kembalikanButton.setText("Sudah Kembali");
        kembalikanButton.setMinimumSize(new java.awt.Dimension(0, 0));
        kembalikanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikanButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkiri.add(kembalikanButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        tabel.add(tabelkiri, gridBagConstraints);

        tabelkanan.setBackground(new java.awt.Color(255, 255, 255));
        tabelkanan.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(84, 88, 113));
        jLabel3.setText("Kode Buku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jLabel3, gridBagConstraints);

        kodeBukuField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        kodeBukuField.setForeground(new java.awt.Color(84, 88, 113));
        kodeBukuField.setText("kdbuku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(kodeBukuField, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator1.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator1, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(84, 88, 113));
        jLabel6.setText("Kode Peminjaman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(jLabel6, gridBagConstraints);

        idPeminjamanField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        idPeminjamanField.setForeground(new java.awt.Color(84, 88, 113));
        idPeminjamanField.setText("kdpinjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(idPeminjamanField, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator2.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator2, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(84, 88, 113));
        jLabel10.setText("Nama Peminjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(jLabel10, gridBagConstraints);

        namaPeminjamField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        namaPeminjamField.setForeground(new java.awt.Color(84, 88, 113));
        namaPeminjamField.setText("nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(namaPeminjamField, gridBagConstraints);

        jSeparator4.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator4.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator4, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(84, 88, 113));
        jLabel11.setText("No. Telepon Peminjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(jLabel11, gridBagConstraints);

        teleponPeminjamField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        teleponPeminjamField.setForeground(new java.awt.Color(84, 88, 113));
        teleponPeminjamField.setText("nomer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(teleponPeminjamField, gridBagConstraints);

        jSeparator5.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator5.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator5, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(84, 88, 113));
        jLabel12.setText("Alamat Peminjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(jLabel12, gridBagConstraints);

        alamatPeminjamField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        alamatPeminjamField.setForeground(new java.awt.Color(84, 88, 113));
        alamatPeminjamField.setText("alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(alamatPeminjamField, gridBagConstraints);

        jSeparator6.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator6.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator6, gridBagConstraints);

        waktuPinjamLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuPinjamLabel.setForeground(new java.awt.Color(84, 88, 113));
        waktuPinjamLabel.setText("Tanggal Pinjam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(waktuPinjamLabel, gridBagConstraints);

        waktuPinjamField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuPinjamField.setForeground(new java.awt.Color(84, 88, 113));
        waktuPinjamField.setText("tgl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(waktuPinjamField, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator3.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator3, gridBagConstraints);

        waktuTenggangLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuTenggangLabel.setForeground(new java.awt.Color(84, 88, 113));
        waktuTenggangLabel.setText("Masa Tenggang Peminjaman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(waktuTenggangLabel, gridBagConstraints);

        waktuTenggangField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuTenggangField.setForeground(new java.awt.Color(84, 88, 113));
        waktuTenggangField.setText("tgl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(waktuTenggangField, gridBagConstraints);

        waktuKembaliLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuKembaliLabel.setForeground(new java.awt.Color(84, 88, 113));
        waktuKembaliLabel.setText("Tanggal Kembali");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        tabelkanan.add(waktuKembaliLabel, gridBagConstraints);

        waktuKembaliField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        waktuKembaliField.setForeground(new java.awt.Color(84, 88, 113));
        waktuKembaliField.setText("tgl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        tabelkanan.add(waktuKembaliField, gridBagConstraints);

        jSeparator7.setBackground(new java.awt.Color(243, 237, 237));
        jSeparator7.setForeground(new java.awt.Color(243, 237, 237));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        tabelkanan.add(jSeparator7, gridBagConstraints);

        scrollPane.setViewportView(tabelkanan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tabel.add(scrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        add(tabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        parent.previousCard();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void kembalikanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanButtonActionPerformed
        // TODO add your handling code here:
        if(Util.askConfirmation("Apakah buku sudah kembali?", "Pengembalian Buku")){
            kembalikan();
        }
    }//GEN-LAST:event_kembalikanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatPeminjamField;
    private javax.swing.JButton btnKembali;
    private perpustakaan.ui.classes.ImageLabel coverLabel;
    private javax.swing.JPanel headerKiri;
    private javax.swing.JLabel idPeminjamanField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton kembalikanButton;
    private javax.swing.JLabel kodeBukuField;
    private javax.swing.JLabel namaPeminjamField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel tabel;
    private javax.swing.JPanel tabelkanan;
    private javax.swing.JPanel tabelkiri;
    private javax.swing.JLabel teleponPeminjamField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel waktuKembaliField;
    private javax.swing.JLabel waktuKembaliLabel;
    private javax.swing.JLabel waktuPinjamField;
    private javax.swing.JLabel waktuPinjamLabel;
    private javax.swing.JLabel waktuTenggangField;
    private javax.swing.JLabel waktuTenggangLabel;
    // End of variables declaration//GEN-END:variables

}
